import { StyleSheet } from "react-native";

export const occurrenceDetailsStyles = StyleSheet.create({
  header: {
    marginTop: 20,
    backgroundColor: "#6C2020",
    padding: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  closeButton: { color: "#fff", fontSize: 14 },
  container: { backgroundColor: "#f9f9f9" },
  card: {
    backgroundColor: "#fff",
    margin: 16,
    padding: 12,
    borderRadius: 8,
    elevation: 2,
  },
  title: { fontSize: 20, fontWeight: "bold", marginBottom: 4 },
  status: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6C2020",
    marginBottom: 8,
  },
  description: { fontSize: 16, marginBottom: 8 },
  location: { fontSize: 14, color: "#555", marginBottom: 4 },
  date: { fontSize: 12, color: "#777", marginBottom: 4 },
  gps: { fontSize: 12, color: "#777", marginBottom: 8 },
  mapButton: {
    marginLeft: 12,
    color: "#6C2020",
    fontWeight: "600",
    fontSize: 14,
    textDecorationLine: "underline",
  },
  section: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    color: "#6C2020",
  },
  image: { width: "100%", height: 200, borderRadius: 8, marginBottom: 12 },
  signature: {
    width: "100%",
    height: 120,
    resizeMode: "contain",
    borderRadius: 8,
  },
  signatureLabel: { fontSize: 12, color: "#666", marginTop: 4 },
  empty: { fontSize: 14, color: "#999", marginBottom: 12 },
  timeline: { fontSize: 14, marginBottom: 4 },
});
